export const ROUTES = {
  home: "/",
  register: "/register",
  login: "/login",
  dashboard: "/dashboard",
  profile: "/profile",
  shareProfile: "/profile/share",
  settings: "/settings",
  marketplace: "/marketplace",
  skillAssessments: "/skill-assessments",
  challenges: "/challenges",
  messages: "/messages",
  notifications: "/notifications",
  projects: "/projects",
  publicProfile: (slug: string) => `/u/${slug}`,
  publicProject: (slug: string, projectId: string) => `/u/${slug}/projects/${projectId}`,
} as const;
