export const ROUTES = {
  home: "/",
  register: "/register",
  login: "/login",
  dashboard: "/dashboard",
  profile: "/profile",
  shareProfile: "/profile/share",
  settings: "/settings",
  marketplace: "/marketplace",
  createService: "/marketplace/create-service",
  serviceDetail: (id: string) => `/marketplace/services/${id}`,
  serviceRequests: "/requests",
  serviceRequestDetail: (id: string) => `/requests/${id}`,
  orders: "/orders",
  orderDetail: (id: string) => `/orders/${id}`,
  skillAssessments: "/skill-assessments",
  skillAssessmentDetail: (skillId: string) => `/skill-assessments/${skillId}`,
  assessmentDetail: (id: string) => `/assessments/${id}`,
  assessmentResult: (id: string) => `/assessments/${id}/result`,
  challenges: "/challenges",
  messages: "/messages",
  conversationDetail: (id: string) => `/messages/${id}`,
  notifications: "/notifications",
  projects: "/projects",
  questionBank: "/admin/question-bank",
  createQuestion: "/admin/question-bank/new",
  questionDetail: (id: string) => `/admin/question-bank/${id}`,
  userManagement: "/admin/users",
  practicalAssessments: "/practical-assessments",
  practicalAssessmentDetail: (id: string) => `/practical-assessments/${id}`,
  practicalAttempt: (id: string) => `/practical-attempts/${id}`,
  practicalAttemptResult: (id: string) => `/practical-attempts/${id}/result`,
  adminPracticalAssessments: "/admin/practical-assessments",
  adminCreatePracticalAssessment: "/admin/practical-assessments/new",
  adminPracticalAssessmentDetail: (id: string) => `/admin/practical-assessments/${id}`,
  adminPracticalAttempts: "/admin/practical-attempts",
  adminPracticalAttemptDetail: (id: string) => `/admin/practical-attempts/${id}`,
  adminCommunications: "/admin/communications",
  adminCommunicationsNew: "/admin/communications/campaigns/new",
  adminCommunicationsCampaignDetail: (id: string) => `/admin/communications/campaigns/${id}`,
  adminCommunicationsCampaignAnalytics: (id: string) => `/admin/communications/campaigns/${id}/analytics`,
  adminCommunicationsTemplates: "/admin/communications/templates",
  adminCommunicationsSegments: "/admin/communications/segments",
  myLearning: "/my-learning",
  myLearningResourceDetail: (id: string) => `/my-learning/resources/${id}`,
  roadmap: "/roadmap",
  calendar: "/calendar",
  adminResources: "/admin/resources",
  adminCreateResource: "/admin/resources/new",
  adminResourceDetail: (id: string) => `/admin/resources/${id}`,
  publicProfile: (slug: string) => `/u/${slug}`,
  publicProject: (slug: string, projectId: string) => `/u/${slug}/projects/${projectId}`,
} as const;
