export const ROUTES = {
  home: "/",
  register: "/register",
  login: "/login",
  dashboard: "/dashboard",
  profile: "/profile",
  shareProfile: "/profile/share",
  settings: "/settings",
  marketplace: "/marketplace",
  createService: "/marketplace/create-service",
  serviceDetail: (id: string) => `/marketplace/services/${id}`,
  serviceRequests: "/requests",
  serviceRequestDetail: (id: string) => `/requests/${id}`,
  orders: "/orders",
  orderDetail: (id: string) => `/orders/${id}`,
  skillAssessments: "/skill-assessments",
  challenges: "/challenges",
  messages: "/messages",
  conversationDetail: (id: string) => `/messages/${id}`,
  notifications: "/notifications",
  projects: "/projects",
  questionBank: "/admin/question-bank",
  createQuestion: "/admin/question-bank/new",
  questionDetail: (id: string) => `/admin/question-bank/${id}`,
  publicProfile: (slug: string) => `/u/${slug}`,
  publicProject: (slug: string, projectId: string) => `/u/${slug}/projects/${projectId}`,
} as const;
